use_frameworks!
platform :ios, '10.0'

target 'SnapshotTesting-Nimble_Example' do

  target 'SnapshotTesting-Nimble_ExampleTests' do
    inherit! :search_paths

    pod 'SnapshotTesting-Nimble', :path => '../'
    pod 'Quick', '~> 2.1.0'
    pod 'Nimble', '~> 8.0.2'
  end
end
